### PR TITLE
Replaced jank GUI by ViaMCP's slider

### PR DESCRIPTION
**Pull request by Nixuge**
Title again, 95% of the work was already done, just tied up things a bit and ported to Forge

Didn't delete GuiProtocolSelector even tho it's unused as ViaMCP doesn't seem to have deleted it either?

### CODE REVIEW

**Comment by Nixuge** [comment]
Oops seems like my previous PR is in there too, it's basically useless now tho, I can open another PR if you want to keep things a bit cleaner

**Comment by FlorianMichael** [comment]
No thanks, I want ViaForge to keep the GUI, the code of the slider is just way too bad, I might make a better slider sometime, because you could then also add.

**Comment by Nixuge** [comment]
I agree the slider's code isn't the best, but is there really a need to keep only the horrendous GUI instead ?

**Comment by FlorianMichael** [comment]
I will look into a "good" implementation/solution for both slider and slot gui

**Pull request closed without merging**
